[package]
name = "simple-json-parser"
version = "0.1.0"
authors = ["jk <jk.hao@edu.pku.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[features]
no_std = []